### ISSUE TITLE
Problem when building this step

### ISSUE THREAD

**Issue by AntonioFerreira94** [FutureWorkshops/bitrise-step-create-apple-documentation#4]
Hello Igor,

Sorry to disturb you again, but even with the updated step, it keeps getting an error.

Configs:
  * jazzy_configuration: 
  * project_path: "/Users/vagrant/git/Project Title"
  * language: swift
  * author: Project Title
  * sdk: iphone
  * version: 1.0.0
  * framework_root: "/Users/vagrant/git/Project Title"
  * module: Project Title (Development)
  * scheme: Project Title (Development)
  * acl: public
  * output: ./docs
  * readme: ./README.md
  * title: Project Title
  * copyright: 
  * umbrella_header:

I'm using the latest stack, could you also give more information when the build fails?

**Comment by andrewmarmion** [comment]
@AntonioFerreira94 Did you manage to get this to work at all?

**Comment by AntonioFerreira94** [comment]
Hey @andrewmarmion, unfortunately I didn't manage to make this work. I also didn't got any response from the creator, but from what I searched, you could create 2 steps: One to install jazzy (brew install jazzy), and other one run it on your project.

**Comment by andrewmarmion** [comment]
@AntonioFerreira94  Thanks for your response. I figured that was the way. How do you export out your documentation once it is created?

**Comment by igorcferreira** [comment]
Hello @AntonioFerreira94, sorry for the delay on the response.

I did some tests with the version 1.1.0 to check what could be causing your issue, and I believe that the source of failure is the configuration:

`- module: Project Title (Development)`

This configuration should match the module name of the framework being built. So, it needs to match $PRODUCT_MODULE_NAME from the target build settings. If your target is named "Project Title (Development)", and you are not setting a custom value for PRODUCT_MODULE_NAME, Xcode will resolve it to "Project_Title__Development_", since a module cannot have non-alphanumeric characters on its product name.

So, your configuration should look similar to:

```yaml
inputs:
- project_path:  "/Users/vagrant/git/Project Title"
- language: swift
- author: Project Title
- sdk: iphone
- version: 1.0.0
- framework_root: "/Users/vagrant/git/Project Title"
- module: Project_Title__Development_
- scheme: Project Title (Development)
- acl: public
- output: ./docs
- readme: ./README.md
- title: Project Title
```

In the latest version (where I included some fixes) I added a test case that showcases the usage of this step for projects with this configuration. This is currently being reviewed on PR #5

Regarding more information when the build fails: I also did some changes to include more messages, but, I'm already outputting Jazzy build messages. So, I don't believe I would be able to add a more descritive error message, since Jazzy would not return an error code that I would be able to match to a user facing message.
